[package]
name = "meilitool"
description = "A CLI to edit a Meilisearch database from the command line"
version.workspace = true
authors.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] } #unified
clap = { workspace = true, features = ["env"] } #unified
dump = { workspace = true } #unified
file-store = { workspace = true } #unified
indexmap = { workspace = true, features = ["rayon"] } #unified
meilisearch-auth = { workspace = true } #unified
meilisearch-types = { workspace = true } #unified
serde = { workspace = true, features = ["rc"] } #unified
serde_json = { workspace = true, features = ["raw_value"] } #unified
tempfile = { workspace = true } #unified
time = { workspace = true, features = ["macros", "serde", "serde-human-readable", "serde-well-known"] } #unified
uuid = { workspace = true, features = ["serde", "v7"] } #unified
