[package]
name = "async-openai"
version = "0.28.1"
authors = ["Himanshu Neema"]
categories = ["api-bindings", "web-programming", "asynchronous"]
keywords = ["openai", "async", "openapi", "ai"]
description = "Rust library for OpenAI"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/64bit/async-openai"
repository = "https://github.com/64bit/async-openai"

[features]
default = []
realtime = ["dep:tokio-tungstenite"]
# Bring your own types
byot = []

[dependencies]
async-openai-macros = { workspace = true } #unified
backoff = { workspace = true, features = ["futures"] } #unified
base64 = { workspace = true } #unified
futures = { workspace = true } #unified
rand = { workspace = true, features = ["small_rng"] } #unified
http-client = { workspace = true } #unified
reqwest-eventsource = { workspace = true } #unified
serde = { workspace = true, features = ["rc"] } #unified
serde_json = { workspace = true, features = ["preserve_order", "raw_value"] } #unified
thiserror = "2.0.11"
tokio = { workspace = true, features = ["full", "net", "process", "rt", "rt-multi-thread", "signal", "sync", "time"] } #unified
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.13", features = ["codec", "io-util"] }
tracing = { workspace = true } #unified
derive_builder = { workspace = true } #unified
secrecy = { workspace = true } #unified
bytes = { workspace = true } #unified
eventsource-stream = "0.2.3"
tokio-tungstenite = { version = "0.26.1", optional = true, default-features = false }

[dev-dependencies]
tokio-test = "0.4.4"
serde_json = { workspace = true, features = ["preserve_order", "raw_value"] } #unified

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
