[package]
name = "index-scheduler"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] } #unified
bincode = { workspace = true } #unified
byte-unit = { version = "5.1.6", features = ["byte", "serde"] }
bytes = { workspace = true } #unified
bumpalo = { workspace = true } #unified
bumparaw-collections = "0.1.4"
convert_case = { workspace = true } #unified
csv = { workspace = true } #unified
derive_builder = { workspace = true } #unified
dump = { workspace = true } #unified
enum-iterator = "2.3.0"
file-store = { workspace = true } #unified
flate2 = { workspace = true } #unified
hashbrown = { workspace = true } #unified
http-client = { workspace = true } #unified
indexmap = { workspace = true, features = ["rayon", "serde"] } #unified
meilisearch-auth = { workspace = true } #unified
meilisearch-types = { workspace = true } #unified
memmap2 = { workspace = true } #unified
page_size = "0.6.0"
rayon = { workspace = true } #unified
roaring = { workspace = true } #unified
serde = { workspace = true, features = ["rc"] } #unified
serde_json = { workspace = true, features = ["raw_value"] } #unified
tar = { workspace = true } #unified
synchronoise = "1.0.1"
tempfile = { workspace = true } #unified
thiserror = "2.0.17"
time = { workspace = true, features = ["serde", "serde-human-readable"] } #unified
tracing = { workspace = true } #unified
uuid = { workspace = true, features = ["v7"] } #unified
backoff = { workspace = true, features = ["futures"] } #unified
rusty-s3 = "0.8.1"
tokio = { workspace = true, features = ["fs", "macros", "net", "process", "rt", "rt-multi-thread", "signal", "sync", "time"] } #unified
urlencoding = { workspace = true } #unified

[dev-dependencies]
big_s = { workspace = true } #unified
crossbeam-channel = "0.5.15"
insta = { workspace = true } #unified
maplit = { workspace = true } #unified
meili-snap = { workspace = true } #unified

[features]
enterprise = ["meilisearch-types/enterprise"]
