[package]
name = "search"
version = "0.13.1"
authors = ["Cl√©ment Renault <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
byte-unit = { version = "4.0.9", default-features = false, features = ["std"] }
heed = { git = "https://github.com/Kerollmops/heed", tag = "v0.12.1" }
log = "0.4.14"
milli = { path = "../milli" }
serde_json = "1.0.62"
stderrlog = "0.5.1"
structopt = { version = "0.3.21", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = "0.3.2"
