[package]
name = "meilisearch-types"
version = "0.29.0"
authors = ["marin <postma.marin@protonmail.com>"]
edition = "2021"

[dependencies]
actix-web = { version = "4.0.1", default-features = false }
csv = "1.1.6"
either = { version = "1.6.1", features = ["serde"] }
enum-iterator = "1.2.0"
fst = "0.4.7"
milli = { git = "https://github.com/meilisearch/milli.git", branch = "indexation-abortion" }
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
roaring = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"
time = { version = "0.3.7", features = ["serde-well-known", "formatting", "parsing", "macros"] }
tokio = "1.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
meili-snap = { path = "../meili-snap" }
insta = "1.19.1"

[features]
test-traits = ["proptest", "proptest-derive"]
