[package]
name = "meilisearch-types"
version = "0.16.0"
license = "MIT"
authors = ["Cl√©ment Renault <renault.cle@gmail.com>"]
edition = "2018"

[dependencies.zerocopy]
version = "0.3.0"
optional = true

[dependencies.serde]
version = "1.0.117"
features = ["derive"]
optional = true

[features]
default = ["serde", "zerocopy"]
