[package]
name = "meilisearch-types"
version = "1.0.0"
authors = ["marin <postma.marin@protonmail.com>"]
edition = "2021"

[dependencies]
actix-web = { version = "4.3.0", default-features = false }
anyhow = "1.0.69"
convert_case = "0.6.0"
csv = "1.1.6"
deserr = "0.4.1"
either = { version = "1.8.1", features = ["serde"] }
enum-iterator = "1.2.0"
file-store = { path = "../file-store" }
flate2 = "1.0.25"
fst = "0.4.7"
memmap2 = "0.5.8"
milli = { path = "../milli", default-features = false }
roaring = { version = "0.10.1", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde-cs = "0.2.4"
serde_json = "1.0.92"
tar = "0.4.38"
tempfile = "3.3.0"
thiserror = "1.0.38"
time = { version = "0.3.17", features = ["serde-well-known", "formatting", "parsing", "macros"] }
tokio = "1.25"
uuid = { version = "1.3.0", features = ["serde", "v4"] }

[dev-dependencies]
insta = "1.26.0"
meili-snap = { path = "../meili-snap" }

[features]
# all specialized tokenizations
default = ["milli/default"]

# chinese specialized tokenization
chinese = ["milli/chinese"]
# hebrew specialized tokenization
hebrew = ["milli/hebrew"]
# japanese specialized tokenization
japanese = ["milli/japanese"]
# thai specialized tokenization
thai = ["milli/thai"]
