[package]
name = "meilisearch-types"
version = "0.30.0"
authors = ["marin <postma.marin@protonmail.com>"]
edition = "2021"

[dependencies]
actix-web = { version = "4.2.1", default-features = false }
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"

[features]
test-traits = ["proptest", "proptest-derive"]
