[package]
name = "async-openai-macros"
version = "0.1.0"
authors = ["Himanshu Neema"]
keywords = ["openai", "macros", "ai"]
description = "Macros for async-openai"
edition = "2021"
license = "MIT"
homepage = "https://github.com/64bit/async-openai"
repository = "https://github.com/64bit/async-openai"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
