[package]
name = "meilisearch-auth"
version = "1.0.0"
edition = "2021"

[dependencies]
base64 = "0.13.1"
enum-iterator = "1.2.0"
hmac = "0.12.1"
maplit = "1.0.2"
meilisearch-types = { path = "../meilisearch-types" }
rand = "0.8.5"
roaring = { version = "0.10.1", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
sha2 = "0.10.6"
thiserror = "1.0.38"
time = { version = "0.3.17", features = ["serde-well-known", "formatting", "parsing", "macros"] }
uuid = { version = "1.2.2", features = ["serde", "v4"] }
