[package]
name = "meilisearch"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

default-run = "meilisearch"

[dependencies]
actix-cors = "0.7.1"
actix-http = { version = "3.11.2", default-features = false, features = [
    "compress-brotli",
    "compress-gzip",
    "rustls-0_23",
] }
actix-utils = "3.0.1"
actix-web = { version = "4.12.0", default-features = false, features = [
    "macros",
    "compress-brotli",
    "compress-gzip",
    "cookies",
    "rustls-0_23",
] }
anyhow = { workspace = true } #unified
bstr = { workspace = true } #unified
byte-unit = { version = "5.1.6", features = ["byte", "serde"] }
bytes = { workspace = true } #unified
bumpalo = { workspace = true } #unified
clap = { workspace = true, features = ["env"] } #unified
crossbeam-channel = "0.5.15"
deserr = { workspace = true } #unified
dump = { workspace = true } #unified
either = { workspace = true, features = ["serde"] } #unified
file-store = { workspace = true } #unified
flate2 = { workspace = true } #unified
fst = { workspace = true } #unified
futures = { workspace = true } #unified
futures-util = "0.3.31"
index-scheduler = { workspace = true } #unified
http-client = { workspace = true } #unified
indexmap = { workspace = true, features = ["rayon"] } #unified
is-terminal = "0.4.17"
itertools = { workspace = true } #unified
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
lazy_static = "1.5.0"
meilisearch-auth = { workspace = true } #unified
meilisearch-types = { workspace = true } #unified
memmap2 = { workspace = true } #unified
mimalloc = { workspace = true } #unified
mime = { workspace = true } #unified
num_cpus = "1.17.0"
obkv = { workspace = true } #unified
once_cell = { workspace = true } #unified
ordered-float = "5.1.0"
parking_lot = "0.12.5"
permissive-json-pointer = { workspace = true } #unified
pin-project-lite = "0.2.16"
platform-dirs = "0.3.0"
prometheus = { version = "0.14.0", features = ["process"] }
rand = { workspace = true, features = ["small_rng"] } #unified
rayon = { workspace = true } #unified
regex = { workspace = true } #unified
rustls = { version = "0.23.36", features = ["ring"], default-features = false }
rustls-pki-types = { version = "1.13.0", features = ["alloc"] }
rustls-pemfile = "2.2.0"
segment = { version = "0.2.6" }
serde = { workspace = true, features = ["rc"] } #unified
serde_json = { workspace = true, features = ["raw_value"] } #unified
sha2 = { workspace = true } #unified
siphasher = "1.0.1"
slice-group-by = "0.3.1"
static-files = { version = "0.3.1", optional = true }
sysinfo = { workspace = true } #unified
tar = { workspace = true } #unified
tempfile = { workspace = true } #unified
thiserror = "2.0.17"
time = { workspace = true, features = ["serde", "serde-human-readable"] } #unified
tokio = { workspace = true, features = ["fs", "macros", "net", "process", "rt", "rt-multi-thread", "signal", "sync", "time"] } #unified
toml = "0.9.8"
uuid = { workspace = true } #unified
serde_urlencoded = "0.7.1"
termcolor = "1.4.1"
url = { workspace = true } #unified
tracing = { workspace = true } #unified
tracing-subscriber = { version = "0.3.20", features = ["json"] }
tracing-trace = { workspace = true } #unified
tracing-actix-web = "0.7.19"
build-info = { workspace = true } #unified
roaring = { workspace = true, features = ["serde"] } #unified
mopa-maintained = "0.2.3"
utoipa = { workspace = true } #unified
utoipa-scalar = { version = "0.3.0", optional = true, features = ["actix-web"] }
async-openai = { workspace = true } #unified
secrecy = { workspace = true, features = ["serde"] } #unified
actix-web-lab = { version = "0.24.3", default-features = false }
urlencoding = { workspace = true } #unified
backoff = { workspace = true, features = ["futures"] } #unified
humantime = { version = "2.3.0", default-features = false }
cidr = { workspace = true } #unified

[dev-dependencies]
actix-rt = "2.11.0"
brotli = "8.0.2"
insta = { workspace = true, features = ["json"] } #unified
manifest-dir-macros = "0.1.18"
maplit = { workspace = true } #unified
meili-snap = { workspace = true } #unified
temp-env = "0.3.6"
wiremock = "0.6.5"
yaup = "0.3.1"

[build-dependencies]
anyhow = { workspace = true, optional = true, features = ["backtrace"] } #unified
cargo_toml = { version = "0.22.3", optional = true }
hex = { workspace = true, optional = true } #unified
reqwest = { workspace = true, optional = true, features = ["json", "multipart", "rustls-tls-native-roots", "stream"] } #unified
sha-1 = { version = "0.10.1", optional = true }
static-files = { version = "0.3.1", optional = true }
tempfile = { workspace = true, optional = true } #unified
zip = { version = "6.0.0", optional = true }

[features]
default = ["meilisearch-types/all-tokenizations", "mini-dashboard"]
swagger = ["utoipa-scalar"]
test-ollama = []
mini-dashboard = [
    "static-files",
    "anyhow",
    "cargo_toml",
    "hex",
    "reqwest",
    "sha-1",
    "tempfile",
    "zip",
]
chinese = ["meilisearch-types/chinese"]
chinese-pinyin = ["meilisearch-types/chinese-pinyin"]
enterprise = ["meilisearch-types/enterprise", "index-scheduler/enterprise"]
hebrew = ["meilisearch-types/hebrew"]
japanese = ["meilisearch-types/japanese"]
korean = ["meilisearch-types/korean"]
thai = ["meilisearch-types/thai"]
greek = ["meilisearch-types/greek"]
khmer = ["meilisearch-types/khmer"]
vietnamese = ["meilisearch-types/vietnamese"]
swedish-recomposition = ["meilisearch-types/swedish-recomposition"]
german = ["meilisearch-types/german"]
turkish = ["meilisearch-types/turkish"]

[package.metadata.mini-dashboard]
assets-url = "https://github.com/meilisearch/mini-dashboard/releases/download/v0.3.0/build.zip"
sha1 = "cdd17ac43cd57d8bf1a889759644200f74514fba"
