[package]
name = "meilisearch-auth"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = { workspace = true } #unified
enum-iterator = "2.3.0"
hex = { workspace = true } #unified
hmac = "0.12.1"
maplit = { workspace = true } #unified
meilisearch-types = { workspace = true } #unified
rand = { workspace = true, features = ["small_rng"] } #unified
roaring = { workspace = true } #unified
serde = { workspace = true, features = ["rc"] } #unified
serde_json = { workspace = true, features = ["raw_value"] } #unified
sha2 = { workspace = true } #unified
thiserror = "2.0.17"
time = { workspace = true, features = ["serde", "serde-human-readable"] } #unified
uuid = { workspace = true, features = ["v7"] } #unified
