[package]
name = "xtask"
version.workspace = true
authors.workspace = true
description = "Workspace automation tool following the xtask pattern <https://github.com/matklad/cargo-xtask>"
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] } #unified
build-info = { workspace = true } #unified
cargo_metadata = "0.23.1"
clap = { workspace = true, features = ["env"] } #unified
futures-core = "0.3.31"
futures-util = "0.3.31"
reqwest = { workspace = true, features = ["blocking", "multipart", "rustls-tls-native-roots"] } #unified
semver = "1.0.27"
serde = { workspace = true, features = ["rc"] } #unified
serde_json = { workspace = true, features = ["preserve_order", "raw_value"] } #unified
sha2 = { workspace = true } #unified
sysinfo = { workspace = true } #unified
time = { workspace = true, features = ["formatting", "parsing", "serde-well-known"] } #unified
tokio = { workspace = true, features = ["fs", "full", "macros", "rt-multi-thread", "sync"] } #unified
tracing = { workspace = true } #unified
tracing-subscriber = { version = "0.3.20", features = ["json"] }
tracing-trace = { workspace = true } #unified
uuid = { workspace = true, features = ["v4"] } #unified
similar-asserts = "1.7.0"
