[package]
name = "openapi-generator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
meilisearch = { workspace = true } #unified
serde_json = { workspace = true, features = ["preserve_order", "raw_value"] } #unified
clap = { workspace = true, features = ["env"] } #unified
anyhow = { workspace = true, features = ["backtrace"] } #unified
utoipa = { workspace = true, features = ["actix_extras", "macros", "non_strict_integers", "openapi_extensions", "preserve_order", "time", "uuid"] } #unified
reqwest = { workspace = true, features = ["json", "multipart", "rustls-tls", "rustls-tls-native-roots", "stream"] } #unified
regex = { workspace = true } #unified
