[package]
name = "openapi-generator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
meilisearch = { path = "../meilisearch" , default-features = false}
serde_json = "1.0"
clap = { version = "4.5.40", features = ["derive"] }
anyhow = "1.0.98"
utoipa = "5.4.0"
