[package]
name = "filter-parser"
description = "The parser for the Meilisearch filter syntax"
publish = false

version.workspace = true
authors.workspace = true
# description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nom = { workspace = true } #unified
nom_locate = "4.2.0"
unescaper = "0.1.6"
levenshtein_automata = { workspace = true } #unified

[dev-dependencies]
insta = { workspace = true, features = ["json", "redactions"] } #unified
