[package]
name = "meilisearch-tokenizer"
version = "0.19.0"
license = "MIT"
authors = ["Kerollmops <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
deunicode = "1.1.1"
slice-group-by = "0.2.6"
