[package]
name = "dump"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] } #unified
flate2 = { workspace = true } #unified
http = "1.3.1"
meilisearch-types = { workspace = true } #unified
once_cell = { workspace = true } #unified
regex = { workspace = true } #unified
roaring = { workspace = true } #unified
serde = { workspace = true, features = ["rc"] } #unified
serde_json = { workspace = true, features = ["raw_value"] } #unified
tar = { workspace = true } #unified
tempfile = { workspace = true } #unified
thiserror = "2.0.17"
time = { workspace = true, features = ["serde", "serde-human-readable"] } #unified
tracing = { workspace = true } #unified
uuid = { workspace = true, features = ["v7"] } #unified

[dev-dependencies]
big_s = { workspace = true } #unified
maplit = { workspace = true } #unified
meili-snap = { workspace = true } #unified
meilisearch-types = { workspace = true } #unified

[features]
enterprise = ["meilisearch-types/enterprise"]
