[package]
name = "http-ui"
description = "The HTTP user interface of the milli search engine"
version = "0.1.0"
authors = ["Cl√©ment Renault <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
grenad = { git = "https://github.com/Kerollmops/grenad.git", rev = "3eb7ad9" }
heed = "0.10.1"
indexmap = "1.6.0"
memmap = "0.7.0"
milli = { path = ".." }
once_cell = "1.4.1"
rayon = "1.5.0"
structopt = { version = "0.3.14", default-features = false, features = ["wrap_help"] }
tempfile = "3.1.0"

# http server
askama = "0.10.1"
askama_warp = "0.10.0"
bytes = "0.5.6"
flate2 = "1.0.19"
futures = "0.3.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.59", features = ["preserve_order"] }
tokio = { version = "0.2", features = ["full"] }
warp = "0.2.2"

# logging
log = "0.4.11"
stderrlog = "0.5.0"
