[package]
name = "json-depth-checker"
description = "A library that indicates if a JSON must be flattened"
publish = false

version.workspace = true
authors.workspace = true
# description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json = "1.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "depth"
harness = false
