[package]
name = "milli"
edition = "2021"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
# edition.workspace = true
license.workspace = true

[dependencies]
big_s = { workspace = true } #unified
bimap = { version = "0.6.3", features = ["serde"] }
bincode = { workspace = true } #unified
bstr = { workspace = true } #unified
bytemuck = { version = "1.24.0", features = ["extern_crate_alloc"] }
byteorder = "1.5.0"
charabia = { version = "0.9.9", default-features = false }
cellulite = "0.3.1-nested-rtxns-2"
concat-arrays = "0.1.2"
convert_case = { workspace = true } #unified
crossbeam-channel = "0.5.15"
# for compatibility with the ureq of hf-hub
danger-ureq = { package = "ureq", version = "2.12.1", features = ["json"] }
deserr = { workspace = true, features = ["actix-web"] } #unified
either = { workspace = true } #unified
flatten-serde-json = { workspace = true } #unified
fst = { workspace = true } #unified
fxhash = "0.2.1"
geojson = "0.24.2"
geoutils = "0.5.1"
grenad = { version = "0.5.0", default-features = false, features = [
    "rayon",
    "tempfile",
] }
heed = { version = "0.22.1-nested-rtxns-6", default-features = false, features = [
    "serde-json",
    "serde-bincode",
] }
http-client = { workspace = true } #unified
indexmap = { workspace = true } #unified
json-depth-checker = { workspace = true } #unified
levenshtein_automata = { workspace = true } #unified
memchr = "2.7.6"
memmap2 = { workspace = true } #unified
obkv = { workspace = true } #unified
once_cell = { workspace = true } #unified
ordered-float = "5.1.0"
rayon = { workspace = true } #unified
roaring = { workspace = true } #unified
rstar = { version = "0.12.2", features = ["serde"] }
serde = { workspace = true, features = ["rc"] } #unified
serde_json = { workspace = true } #unified
slice-group-by = "0.3.1"
smallstr = { version = "0.3.1", features = ["serde"] }
smallvec = "1.15.1"
smartstring = "1.0.1"
tempfile = { workspace = true } #unified
thiserror = "2.0.17"
time = { workspace = true, features = ["serde", "serde-human-readable"] } #unified
uuid = { workspace = true, features = ["serde", "v7"] } #unified
filter-parser = { workspace = true } #unified
itertools = { workspace = true } #unified
csv = { workspace = true } #unified
candle-core = { version = "0.9.1" }
candle-transformers = { version = "0.9.1" }
candle-nn = { version = "0.9.1" }
tokenizers = { version = "0.22.1", default-features = false, features = [
    "onig",
] }
hf-hub = { git = "https://github.com/dureuill/hf-hub.git", branch = "rust_tls", default-features = false, features = [
    "online",
] }
safetensors = "0.6.2"
tiktoken-rs = "0.9.1"
liquid = "0.26.11"
rhai = { version = "1.23.6", features = [
    "serde",
    "no_module",
    "no_custom_syntax",
    "no_time",
    "sync",
] }
arroy = "0.6.4-nested-rtxns"
hannoy = { version = "0.1.5-nested-rtxns", features = ["arroy"] }
rand = { workspace = true, features = ["small_rng"] } #unified
tracing = { workspace = true } #unified
url = { workspace = true, features = ["serde"] } #unified
hashbrown = { workspace = true } #unified
bumpalo = { workspace = true } #unified
bumparaw-collections = "0.1.4"
steppe = { version = "0.4", default-features = false }
thread_local = "1.1.9"
rustc-hash = "2.1.1"
enum-iterator = "2.3.0"
bbqueue = { git = "https://github.com/meilisearch/bbqueue" }
flume = { version = "0.11.1", default-features = false }
utoipa = { workspace = true, features = ["actix_extras"] } #unified
lru = "0.16.3"
twox-hash = { version = "2.1.2", default-features = false, features = [
    "std",
    "xxhash3_64",
    "xxhash64",
] }
geo-types = "=0.7.17" # fixed version: see <https://github.com/meilisearch/meilisearch/pull/6118>
zerometry = "0.3.0"

[dev-dependencies]
mimalloc = { workspace = true } #unified
insta = { workspace = true, features = ["json", "redactions"] } #unified
maplit = { workspace = true } #unified
md5 = { workspace = true } #unified
meili-snap = { workspace = true } #unified
rand = { workspace = true } #unified

[features]
all-tokenizations = ["charabia/default"]

# Use POSIX semaphores instead of SysV semaphores in LMDB
# For more information on this feature, see heed's Cargo.toml
lmdb-posix-sem = ["heed/posix-sem"]

# allow chinese specialized tokenization
chinese = ["charabia/chinese"]
chinese-pinyin = ["chinese", "charabia/chinese-normalization-pinyin"]

enterprise = []

# allow hebrew specialized tokenization
hebrew = ["charabia/hebrew"]

# allow japanese specialized tokenization
japanese = ["charabia/japanese"]
japanese-transliteration = ["charabia/japanese-transliteration"]

# allow korean specialized tokenization
korean = ["charabia/korean"]

# allow thai specialized tokenization
thai = ["charabia/thai"]

# allow greek specialized tokenization
greek = ["charabia/greek"]

# allow khmer specialized tokenization
khmer = ["charabia/khmer"]

# allow vietnamese specialized tokenization
vietnamese = ["charabia/vietnamese"]

# allow german specialized tokenization
german = ["charabia/german-segmentation"]

# force swedish character recomposition
swedish-recomposition = ["charabia/swedish-recomposition"]

# allow turkish specialized tokenization
turkish = ["charabia/turkish"]

# allow CUDA support, see <https://github.com/meilisearch/meilisearch/issues/4306>
cuda = ["candle-core/cuda"]
