name: Look for flaky tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * FRI" # Every Friday at 12:00PM

jobs:
  flaky:
    runs-on: ubuntu-latest
    container:
      # Use ubuntu-18.04 to compile with glibc 2.27, which are the production expectations
      image: ubuntu:18.04
    steps:
    - uses: actions/checkout@v3
    - name: Install needed dependencies
      run: |
        apt-get update && apt-get install -y curl
        apt-get install build-essential -y
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install cargo-flaky
      run: cargo install cargo-flaky
    - name: Run cargo flaky in the dumps
      run: cd dump; cargo flaky -i 100 --release
    - name: Run cargo flaky in the index-scheduler
      run: cd index-scheduler; cargo flaky -i 100 --release
    - name: Run cargo flaky in the auth
      run: cd meilisearch-auth; cargo flaky -i 100 --release
    - name: Run cargo flaky in meilisearch
      run: cd meilisearch; cargo flaky -i 100 --release
