name: Look for flaky tests
on:
  schedule:
    - cron: "0 12 * * FRI" # every friday at 12:00PM

jobs:
  flaky:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-flaky
      run: cargo install cargo-flaky
    - name: Run cargo flaky 100 times
      run: cargo flaky -i 100 --release
