name: Run the indexing fuzzer

on:
  push:
    branches:
      - main

jobs:
  fuzz:
    name: Setup the action
    runs-on: ubuntu-latest
    timeout-minutes: 4320 # 72h
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.91.1

      # Run benchmarks
      - name: Run the fuzzer
        run: |
          cargo run --release --bin fuzz-indexing
